---
- name: "configuration play."
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - os_environment:
        - key: TYPEORM_CONNECTION
          value: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
        - key: TYPEORM_ENTITIES
          value: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
        - key: TYPEORM_HOST
          value: "{{ lookup('env', 'TYPEORM_HOST')}}"
        - key: TYPEORM_PORT
          value: 5432
        - key: TYPEORM_USERNAME
          value: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
        - key: TYPEORM_PASSWORD
          value: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
        - key: TYPEORM_DATABASE
          value: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
        - key: TYPEORM_MIGRATIONS
          value: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
        - key: TYPEORM_MIGRATIONS_DIR
          value: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
        - key: TYPEORM_MIGRATIONS_DIR
          value: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        delay: 5
        timeout: 600

    - name: "install python for Ansible."
      # Your code here
      become: yes
      apt:
        name: python3
        state: latest

    - name: customize ~/.bashrc
      ansible.builtin.lineinfile:
        dest: "~/.bashrc"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ os_environment }}"

  roles:
    # Your code here
    - configure-server
    - configure-prometheus-node-exporter
