---
- name: Copy files from backend
  become: true
  copy:
    src: /home/circleci/project/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: extract zip file
  shell: |
    cd /home/ubuntu/
    tar xzvf backend.tar.gz

- name: Start PM2
  shell: |
    cd /home/ubuntu/
    pm2 stop default
    sudo pm2 start npm --name backend -- start
