---
- name: Copy files from backend
  become: true
  copy:
    src: /home/project/artifact.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Start PM2
  shell: |
    cd /home/ubuntu/
    tar xzvf backend.tar.gz
    cd backend
    sudo npm install -g npm@latest
    sudo npm install -g webpack-dev-server
    sudo npm install
    sudo npm run build
    sudo pm2 start npm --name backend -- start
